"""v001_initial_schema

Revision ID: 0e7dd5642a9b
Revises: 
Create Date: 2026-03-20 15:31:04.549629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e7dd5642a9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('acronym', sa.String(length=80), nullable=True),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('scopus_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('scopus_quartile', sa.String(length=3), nullable=True),
    sa.Column('core_ranking', sa.String(length=3), nullable=True),
    sa.Column('core_score', sa.Integer(), nullable=True),
    sa.Column('lookup_source', sa.String(length=30), nullable=True),
    sa.Column('lookup_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('qs_year_used', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('qs_year', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('application_ref', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=True),
    sa.Column('cv_document_id', sa.UUID(), nullable=True),
    sa.Column('transcript_document_id', sa.UUID(), nullable=True),
    sa.Column('pairing_complete', sa.Boolean(), nullable=True),
    sa.Column('last_composite_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('last_rank', sa.Integer(), nullable=True),
    sa.Column('last_ranking_config_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['evaluation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_ref')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['evaluation_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tiebreak_field', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['evaluation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=False),
    sa.Column('overridden_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('pub_type', sa.String(length=20), nullable=False),
    sa.Column('position_in_cv', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors_raw', sa.Text(), nullable=True),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.Column('total_authors', sa.Integer(), nullable=True),
    sa.Column('first_author', sa.Boolean(), nullable=True),
    sa.Column('contribution_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('raw_citation', sa.Text(), nullable=True),
    sa.Column('conference_location', sa.Text(), nullable=True),
    sa.Column('conference_dates', sa.String(length=100), nullable=True),
    sa.Column('scopus_pct_at_extraction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('core_score_at_extraction', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('extraction_source', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('computed_by', sa.UUID(), nullable=True),
    sa.Column('total_applicants', sa.Integer(), nullable=False),
    sa.Column('scores_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['ranking_configs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['evaluation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('cv_document_id', sa.UUID(), nullable=True),
    sa.Column('transcript_document_id', sa.UUID(), nullable=True),
    sa.Column('bsc_uni_name', sa.Text(), nullable=True),
    sa.Column('bsc_qs_rank', sa.Integer(), nullable=True),
    sa.Column('bsc_qs_normalised', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('msc_uni_name', sa.Text(), nullable=True),
    sa.Column('msc_qs_rank', sa.Integer(), nullable=True),
    sa.Column('msc_qs_normalised', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('bsc_gpa_raw', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('bsc_gpa_scale', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('bsc_gpa_normalised', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('bsc_gpa_normalised_done', sa.Boolean(), nullable=True),
    sa.Column('bsc_gpa_source', sa.String(length=40), nullable=True),
    sa.Column('msc_gpa_raw', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('msc_gpa_scale', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('msc_gpa_normalised', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('msc_gpa_normalised_done', sa.Boolean(), nullable=True),
    sa.Column('msc_gpa_source', sa.String(length=40), nullable=True),
    sa.Column('msc_absent', sa.Boolean(), nullable=True),
    sa.Column('global_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=True),
    sa.Column('nlp_confidence_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_confidence_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_source_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['cv_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['transcript_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_metrics')
    op.drop_table('ranking_results')
    op.drop_table('publications')
    op.drop_table('manual_overrides')
    op.drop_table('documents')
    op.drop_table('ranking_configs')
    op.drop_table('audit_log')
    op.drop_table('applicants')
    op.drop_table('evaluation_sessions')
    op.drop_table('venues')
    op.drop_table('users')
    # ### end Alembic commands ###
