"""v002_full_schema_11_tables

Revision ID: 79f142d7fb55
Revises: ecb932800c60
Create Date: 2026-03-20 22:47:04.907880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79f142d7fb55'
down_revision: Union[str, Sequence[str], None] = 'ecb932800c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('applicants', 'needs_human_review',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applicants', 'pairing_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applicants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_applicants_session', 'applicants', ['session_id'], unique=False)
    op.create_foreign_key(None, 'applicants', 'ranking_configs', ['last_ranking_config_id'], ['id'])
    op.create_foreign_key(None, 'applicants', 'documents', ['transcript_document_id'], ['id'])
    op.create_foreign_key(None, 'applicants', 'documents', ['cv_document_id'], ['id'])
    op.alter_column('audit_log', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('audit_log', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_session_time', 'audit_log', ['session_id', 'occurred_at'], unique=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_documents_applicant', 'documents', ['applicant_id'], unique=False)
    op.alter_column('evaluation_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('evaluation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('extracted_metrics', 'bsc_gpa_normalised_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('extracted_metrics', 'msc_gpa_normalised_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('extracted_metrics', 'msc_absent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('extracted_metrics', 'llm_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('extracted_metrics', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_extracted_applicant', 'extracted_metrics', ['applicant_id'], unique=False)
    op.alter_column('manual_overrides', 'table_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('manual_overrides', 'record_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('manual_overrides', 'overridden_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_overrides_applicant', 'manual_overrides', ['applicant_id'], unique=False)
    op.alter_column('publications', 'extraction_source',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index('idx_publications_applicant', 'publications', ['applicant_id'], unique=False)
    op.create_index('idx_publications_venue', 'publications', ['venue_id'], unique=False)
    op.alter_column('ranking_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ranking_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ranking_results', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_ranking_session', 'ranking_results', ['session_id', 'computed_at'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('venues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_venues_type_name', 'venues', ['venue_type', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_venues_type_name', table_name='venues')
    op.alter_column('venues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'hashed_password')
    op.drop_index('idx_ranking_session', table_name='ranking_results')
    op.alter_column('ranking_results', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ranking_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ranking_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_publications_venue', table_name='publications')
    op.drop_index('idx_publications_applicant', table_name='publications')
    op.alter_column('publications', 'extraction_source',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('idx_overrides_applicant', table_name='manual_overrides')
    op.alter_column('manual_overrides', 'overridden_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('manual_overrides', 'record_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('manual_overrides', 'table_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_extracted_applicant', table_name='extracted_metrics')
    op.alter_column('extracted_metrics', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('extracted_metrics', 'llm_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('extracted_metrics', 'msc_absent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('extracted_metrics', 'msc_gpa_normalised_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('extracted_metrics', 'bsc_gpa_normalised_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('evaluation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('evaluation_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('idx_documents_applicant', table_name='documents')
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('idx_audit_session_time', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.alter_column('audit_log', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('audit_log', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.drop_index('idx_applicants_session', table_name='applicants')
    op.alter_column('applicants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('applicants', 'pairing_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applicants', 'needs_human_review',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('applicants', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
